# Generated by Django 6.0.3 on 2026-04-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('grade', models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Maths', 'Maths'), ('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Integrated Science', 'Integrated Science'), ('Agriculture', 'Agriculture'), ('Social Studies', 'Social Studies'), ('CRE', 'CRE'), ('Creative Art', 'Creative Art'), ('Pretechnical Studies', 'Pretechnical Studies'), ('Creative Arts', 'Creative Arts')], max_length=50)),
                ('marks', models.IntegerField(default=0)),
                ('term', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2026)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term', 'year')},
            },
        ),
    ]
