# Generated by Django 6.0.3 on 2026-04-30 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_assessment_number_student_parent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Integrated Science', 'Integrated Science'), ('Social Studies', 'Social Studies'), ('Religious Education', 'Religious Education'), ('Pre-Technical Studies', 'Pre-Technical Studies'), ('Health Education', 'Health Education'), ('Creative Arts & Sports', 'Creative Arts & Sports'), ('Agriculture & Nutrition', 'Agriculture & Nutrition')], max_length=50),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('singles', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.teacher')),
            ],
        ),
    ]
