# Generated by Django 6.0.3 on 2026-04-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_alter_mark_subject_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
