# Generated by Django 6.0.3 on 2026-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=50),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Integrated Science', 'Integrated Science'), ('Social Studies', 'Social Studies'), ('Religious Education', 'Religious Education'), ('Pre-Technical Studies', 'Pre-Technical Studies'), ('Health Education', 'Health Education'), ('Creative Arts & Sports', 'Creative Arts & Sports'), ('Agriculture & Nutrition', 'Agriculture & Nutrition')], max_length=100),
        ),
    ]
