# Generated by Django 6.0.3 on 2026-05-11 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_borrowrecord_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='assessment_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_birth',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='member_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocation',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
