# Generated by Django 6.0.3 on 2026-05-12 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_book_isbn_remove_borrowrecord_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
