# Generated by Django 6.0.3 on 2026-05-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_borrowrecord_borrow_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ['teacher', 'grade']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'ordering': ['-borrow_date']},
        ),
        migrations.AlterModelOptions(
            name='fine',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['student', 'subject']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='doubles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='singles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='core.book'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='core.borrowrecord'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Integrated Science', 'Integrated Science'), ('Social Studies', 'Social Studies'), ('Religious Education', 'Religious Education'), ('Pre-Technical Studies', 'Pre-Technical Studies'), ('Health Education', 'Health Education'), ('Creative Arts & Sports', 'Creative Arts & Sports'), ('Agriculture & Nutrition', 'Agriculture & Nutrition')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mark',
            name='term',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mark',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
