# Generated by Django 6.0.3 on 2026-05-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
