# Generated by Django 6.0.3 on 2026-06-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_book_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('book_type', models.CharField(choices=[('Textbook', 'Textbook'), ('Setbook', 'Setbook'), ('Guide', 'Guide'), ('Reference', 'Reference')], max_length=50)),
                ('file', models.FileField(upload_to='digital_library_books/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
