# Generated by Django 6.0.3 on 2026-06-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
